import { RegistrationFormData } from '../types/data/registrationDataTypes';

export function buildRegistrationFormData(
  regData: RegistrationFormData,
  boundary: string,
  countryCode: string = 'US'
): string {
  return [
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_firstName"`,
    '',
    regData.firstName,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_lastName"`,
    '',
    regData.lastName,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_email"`,
    '',
    regData.email,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_password"`,
    '',
    regData.password,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_confirmPassword"`,
    '',
    regData.confirmPassword,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_company"`,
    '',
    regData.companyName,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_phone"`,
    '',
    regData.phoneNumber,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_address1"`,
    '',
    regData.addressLineOne,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_address2"`,
    '',
    regData.addressLineTwo,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_city"`,
    '',
    regData.suburbCity,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_stateOrProvince"`,
    '',
    regData.stateProvince,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_postalCode"`,
    '',
    regData.zipPostcode,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_countryCode"`,
    '',
    countryCode,
    `------${boundary}`,
    `Content-Disposition: form-data; name="1_countryCode_display"`,
    '',
    countryCode,
    `------${boundary}`,
    `Content-Disposition: form-data; name="0"`,
    '',
    `[{"fields":[[{"id":"4","type":"text","name":"firstName","label":"First Name","required":true},{"id":"5","type":"text","name":"lastName","label":"Last Name","required":true}],{"id":"1","type":"email","name":"email","label":"Email Address","required":true},{"id":"2","type":"password","name":"password","label":"Password","required":true},{"id":"3","type":"confirm-password","name":"confirmPassword","label":"Confirm Password","required":true},{"id":"6","type":"text","name":"company","label":"Company Name","required":false},{"id":"7","type":"text","name":"phone","label":"Phone Number","required":false},{"id":"8","type":"text","name":"address1","label":"Address Line 1","required":true},{"id":"9","type":"text","name":"address2","label":"Address Line 2","required":false},[{"id":"10","type":"text","name":"city","label":"Suburb/City","required":true},{"id":"12","type":"text","name":"stateOrProvince","label":"State/Province","required":true}],[{"id":"13","type":"text","name":"postalCode","label":"Zip/Postcode","required":true},{"id":"11","type":"select","name":"countryCode","label":"Country","required":true}]],"passwordComplexity":{"minimumNumbers":1,"minimumPasswordLength":7,"minimumSpecialCharacters":1,"requireLowerCase":false,"requireNumbers":false,"requireSpecialCharacters":false,"requireUpperCase":false}},{"lastResult":null},"$K1"]`,
    `------${boundary}--`,
  ].join('\r\n');
}
